scara_setup:
  scara_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder
      - elbow
      - wrist
      - fingerjoint
      - linear

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

#  scara_linear_controller:
#    type: position_controllers/JointTrajectoryController
#    joints: 
#      - linear
#
#    constraints:
#      goal_time: 0.5                   # Override default
#      stopped_velocity_tolerance: 0.02 # Override default
#
#    gains: 
#      linear: {p: 100.0, i: 1.0, d: 0.0, i_clamp_min: -100000, i_clamp_max: 100000}
