scara_setup:
  scara_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - shoulder
      - elbow
      - wrist
      - fingerjoint
      - linear

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

    gains: 
      shoulder: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}
      elbow: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}
      wrist: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}
      fingerjoint: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}
      linear: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}

#  scara_linear_controller:
#    type: effort_controllers/JointTrajectoryController
#    joints: 
#      - linear
#
#    constraints:
#      goal_time: 0.5                   # Override default
#      stopped_velocity_tolerance: 0.02 # Override default
#
#    gains: 
#      linear: {p: 10000.0, i: 1.0, d: 10.0, i_clamp_min: -100000, i_clamp_max: 100000}
